### ISSUE TITLE
Compile Error in building

### ISSUE THREAD

**Issue by blessyyyu** [QuantFabric/QuantFabric#1]
when I `sh build_release.sh`, and compile the XWatcher_0.5.1 failed, the result is below:
```
[ 16%] Linking CXX executable ../XWatcher_0.5.1
/usr/bin/ld: CMakeFiles/XWatcher_0.5.1.dir/WatcherEngine.cpp.o: in function `Utils::LoadXWatcherConfig(char const*, Utils::XWatcherConfig&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) [clone .constprop.0]':
/root/QuantFabric/XWatcher/../Utils/YMLConfig.hpp:578: undefined reference to `YAML::LoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/XWatcher_0.5.1.dir/WatcherEngine.cpp.o: in function `YAML::detail::node_ref::set_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
```
What's more, I write `#include "yaml-cpp/node/parse.h"` on the above of `YMLConfig.hpp`， however it failed both.

GCC: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Environment: Ubuntu20.04 in WSL;
git submodule info:
73e4c4ca771686308be4a7576226923651a0690b Tools (heads/master)
 a04c8b6c9a7f389ae7d8ad9b62a2af02d4959c0a Utils (heads/master)
 b70fcbe4afffebd347ca1e539890917a81f6aa71 XAPI (heads/master)
 43f46333a27c00b60c06b0174ad9412aceed6ff1 XDataPlayer (0.2.0-3-g43f4633)
 f77bf74647bca50c8c8776444a19a5dd0c27ca78 XMarketCenter (0.8.0-4-gf77bf74)
 0c153ea1a99571a5e5a29aa2bc338e4604d10ebf XMonitor (0.9.0-5-g0c153ea)
 0ad397a037e35f999c5f33f13784175945fcdbcb XRiskJudge (0.8.0-4-g0ad397a)
 89d9aeeae468ad6bc12e64fea166f420df534572 XServer (0.8.0-4-g89d9aee)
 8f8118fe93a93c7f0ed2323f66b70fb505278435 XTrader (0.8.0-2-g8f8118f)
 54415c5ef16603bb4355043bcdd316210f6a6992 XWatcher (0.5.0-6-g54415c5)

what can I do to solve the problem?

**Comment by scorpiostudio** [comment]
下载YAML-CPP 0.8.0编译出libyaml-cpp.a后替换到XAPI/YAML-CPP/0.8.0/lib/

**Comment by blessyyyu** [comment]
> 下载YAML-CPP 0.8.0编译出libyaml-cpp.a后替换到XAPI/YAML-CPP/0.8.0/lib/

ok, 已重新编译后通过。（顺便提一下，在OrderSender模块内使用的yaml-cpp 0.6.3版本，同一个三方库使用两个不同版本不好，我在OrderSender模块中改成0.8.0版本，目前编译已全部通过
